In [1]:
import numpy as np

**1. What is the python library? why do we use python libraries?**



*   A Python library is a **collection of pre-written Python code** that provides functionalities to perform specific tasks.
*   These libraries typically **contain reusable functions, classes, and modules** that can be imported and utilized in Python scripts or applications.
*   Python libraries are **designed to simplify programming by providing ready-made solutions for common tasks**, such as numerical computing, data analysis, web development, machine learning, and more.
*   By leveraging Python libraries, **developers can save time and effort** by not having to write code from scratch to implement these functionalities, thus promoting code reusability and efficiency.



**2. What is the differnece between numpy array and list?**


1. **Memory Efficiency:**
Numpy arrays are more memory efficient compared to lists. This is because numpy arrays are homogeneous, meaning they contain elements of the same data type, whereas lists can contain elements of different data types.
2. **Performance**:
Numpy arrays offer better performance for numerical operations compared to lists. Numpy operations are implemented in C, which makes them faster than equivalent operations performed on Python lists.
3. **Functionality:**
Numpy arrays provide a wide range of mathematical functions and operations that are optimized for arrays, such as element-wise operations, linear algebra, Fourier transforms, and more. Lists do not have built-in support for these operations, requiring manual iteration or the use of external libraries.
4. **Ease of Use:**
Lists are more flexible and easier to work with for general-purpose tasks due to their dynamic nature and support for mixed data types. Numpy arrays, being homogeneous, require elements of the same data type, which may sometimes require explicit data type conversion.
5. **Syntax:**
Numpy arrays have a different syntax compared to lists for common operations. For example, while both arrays and lists support indexing and slicing, numpy arrays have additional slicing capabilities like boolean indexing and fancy indexing.

**3. Find the shape, size and dimention of following array?**

In [9]:
arr = [[1,2,3,4],
       [5,6,7,8],
       [9,10,11,12]
       ]

print("Shape of Array",np.shape(arr))
print("Size of Array", np.size(arr))
print("Dimention of Array", np.ndim(arr))

Shape of Array (3, 4)
Size of Array 12
Dimention of Array 2


**4. Write the python code to access the first row of the following array**

In [11]:
arr = [[1,2,3,4],
       [5,6,7,8],
       [9,10,11,12]
       ]

print('first row of the arry is -->>>', arr[0])

first row of the arry is -->>> [1, 2, 3, 4]


**5. How do you access the element at the third row and fourth column from the given numpy array?**

In [13]:
arr = [[1,2,3,4],
       [5,6,7,8],
       [9,10,11,12]
       ]

print('element at third row and fourth column of the arry is -->>>', arr[2][3])

element at third row and fourth column of the arry is -->>> 12


**6. Write code to extract all odd indexed elements from the given numpy array**

In [22]:
arr = [[1,2,3,4],
       [5,6,7,8],
       [9,10,11,12]
       ]

odd_indexed_elements = [i[1::2]for i in arr]
print(odd_indexed_elements)

[[2, 4], [6, 8], [10, 12]]


**7. How can you generate 3X3 matrix with values between 0 and 1?**

In [61]:
print('Matrix of 3X3 with values between 0 and 1\n',np.random.randint(0,2, size=(3,3)))

Matrix of 3X3 with values between 0 and 1
 [[0 1 1]
 [1 0 0]
 [1 1 1]]


**8. Describe the difference between np.random.rand and np.random.randn?**

np.random.rand
1. This function generates random numbers from a uniform distribution over the interval [0, 1).
2. The syntax for np.random.rand is np.random.rand(d0, d1, ..., dn), where d0, d1, ..., dn are the dimensions of the output array.
3. It returns an array of shape (d0, d1, ..., dn) filled with random numbers sampled from a uniform distribution over [0, 1).
4. All numbers in the output array are equally likely to occur.

np.random.randn
1. This function generates random numbers from a standard normal distribution (mean=0, standard deviation=1).
2. The syntax for np.random.randn is np.random.randn(d0, d1, ..., dn), similar to np.random.rand.
3. It returns an array of shape (d0, d1, ..., dn) filled with random numbers sampled from a standard normal distribution.
4. The distribution is centered around 0, and most of the values lie within the range of -3 to 3 (approximately) due to the properties of the normal distribution.

**9. Write a code to increase the dimention of following array?**

In [42]:
arr = [[1,2,3,4],
       [5,6,7,8],
       [9,10,11,12]
       ]

 # Increase its dimension by adding a new axis along the second dimension (columns)
print(np.expand_dims(arr,axis = 0))
print('-'*20)
print(np.expand_dims(arr,axis = 1))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
--------------------
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


**10. How to transpose the following array in numpy?**

In [60]:
arr = [[1,2,3,4],
       [5,6,7,8],
       [9,10,11,12]
       ]

print('Transposed array\n', np.transpose(arr))

Transposed array
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


**11. Consider the following matrices and perform the following operations using python**



1.   Index wise multiplication



In [54]:
A = np.array ([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

B = np.array ([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(A*B)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]




2.   Matrix Multiplication


*   Matrix multiplication is not possible as number of rows of matrix A and number of columns of matrix B are not equal.






In [56]:
A = np.array ([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

B = np.array ([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(np.dot(A,B))

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)



3.   Add Both matrices




In [59]:
print('Addition of both the matrices is\n' , A+B)

Addition of both the matrices is
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]




4.   Substract matrix B from matrix A




In [62]:
print(A-B)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]




5.   Devide matrix B by matrix A




In [63]:
print(A/B)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**12. Which function in numpy can be used to swap the byte order of an array?**



1.   In NumPy, you can use the byteswap() method to swap the byte order of an array. This method changes the byte order of the elements in the array to the specified byte order



**13. What is the sighnificance of np.linalg.inv function?**


1.   The np.linalg.inv() function in NumPy is used to compute the inverse of a square matrix.
2.   The input matrix must be square. If it's not, NumPy will raise a LinAlgError
3.   If the matrix is singular (i.e., its determinant is zero), the function will raise a LinAlgError because singular matrices do not have inverses.
4.   Computing the inverse of a matrix is computationally expensive, especially for large matrices, and may not always be numerically stable.



**14. What does the np.reshape function do, and how it is used?**


1.   The np.reshape() function in NumPy is used to change the shape (dimensions) of an array without changing its data.
2.   It allows you to specify the new shape of the array, and NumPy will rearrange the elements of the array to fit the new shape while preserving the order of the elements.



In [67]:
arr =  np.array([1,2,3,4,5,6,7,8,9])
np.reshape(arr, (3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**15. What is the brodcasting in numpy?**


1. Broadcasting in NumPy is a powerful mechanism that allows arrays with different shapes to be combined or operated upon together.
2. This enables you to perform element-wise operations on arrays of different shapes without having to explicitly reshape or duplicate the arrays.
3. When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions and works its way backward. Two dimensions are compatible if they are equal, or if one of them is 1. Arrays with fewer dimensions are padded with ones on their leading (left) side.



In [70]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Create a 1D array
arr2 = np.array([10, 20, 30])

# Perform broadcasting to add arr2 to each row of arr1
result = arr1 + arr2

# Print the result
print("Result of broadcasting:")
print(result)

Result of broadcasting:
[[11 22 33]
 [14 25 36]]
